version: '3'
services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.production
    image: tarascloyd/devops-for-programmers-project-74
    command: npm test
    environment:
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_HOST: $DATABASE_HOST
    depends_on:
      - db
    
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password