version: '3'
services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.production
    image: tarascloyd/devops-for-programmers-project-74
    command: npm test
    depends_on:
      - db
    
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password